- name: install and start inginx
  hosts:  web
  become: yes
  tasks:  
  - name: install inginx
    ansible.builtin.package:
      name: nginx
      state:  present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state:  started
      enabled: yes